# Generated by Django 3.2.5 on 2021-08-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthdata',
            options={},
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='automotiveLabelCount',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='bloodType',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='cyclingLabelCount',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='distanceCovered',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='heartRate',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='runningLabelCount',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='stationaryLabelCount',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='stepsCount',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='timeStamp',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='unknownLabelCount',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='userToken',
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='walkingLabelCount',
        ),
        migrations.AddField(
            model_name='healthdata',
            name='automotivelabelcount',
            field=models.IntegerField(blank=True, db_column='automotiveLabelCount', null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='bloodtype',
            field=models.TextField(blank=True, db_column='bloodType', null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='cyclinglabelcount',
            field=models.IntegerField(blank=True, db_column='cyclingLabelCount', null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='distancecovered',
            field=models.FloatField(blank=True, db_column='distanceCovered', null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='game',
            field=models.TextField(blank=True, db_column='game', null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='heartrate',
            field=models.IntegerField(blank=True, db_column='heartRate', null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='runninglabelcount',
            field=models.IntegerField(blank=True, db_column='runningLabelCount', null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='stationarylabelcount',
            field=models.IntegerField(blank=True, db_column='stationaryLabelCount', null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='stepscount',
            field=models.IntegerField(blank=True, db_column='stepsCount', null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='timestamp',
            field=models.TextField(blank=True, db_column='timeStamp', null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='unknownlabelcount',
            field=models.IntegerField(blank=True, db_column='unknownLabelCount', null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='usertoken',
            field=models.TextField(blank=True, db_column='userToken', null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='walkinglabelcount',
            field=models.IntegerField(blank=True, db_column='walkingLabelCount', null=True),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='sex',
            field=models.TextField(blank=True, null=True),
        ),
    ]
